---
title: "mp4_cathy"
author: "Cathy Lee"
date: "29 April 2018"
output: html_document
---

```{r Setup, message=FALSE, warning=FALSE}
# Set up the environment
library(mdsr)
library(RMySQL)
library(tidyverse)
library(ggthemes)
library(RColorBrewer)
library(ggpubr)
# Available databases: airlines, citibike, fec, imdb, lahman, nyctaxi
db <- dbConnect_scidb(dbname = "imdb")
```

```{r}
# Get the table from SQL
# by joining cast_info, person_info, movie_info, and movie_info_idx
q1 <- "
SELECT t.id, t.title, t.production_year, mii.info AS genre,
mii2.info AS budget, mii3.info AS gross, cn.name AS company
FROM title t 
JOIN movie_info mii ON mii.movie_id = t.id
JOIN movie_info mii2 ON mii2.movie_id = t.id
JOIN movie_info mii3 ON mii3.movie_id = t.id
JOIN movie_companies mc ON mc.movie_id = t.id
JOIN company_name cn ON cn.id = mc.company_id
WHERE t.kind_id = 1
 AND mii.info_type_id = 3
 AND mii2.info_type_id = 105
 AND mii2.info LIKE '$%'
 AND mii3.info_type_id = 107
 AND cn.country_code = '[us]'
 AND production_year > 1980
 AND mii3.info LIKE '%(USA)'
ORDER BY mii2.info desc;
"
movies_all_info <- db %>%
  dbGetQuery(q1)
```

```{r}
# top 10 most popular genres (most movies listed in that genre)
top_genres <- movies_all_info %>%
  group_by(genre) %>%
  summarize(num_movies = n()) %>%
  arrange(desc(num_movies)) %>%
  head(10)
```

```{r}
# filter out top 10 genres
top_genres_info <- movies_all_info %>% 
  filter(genre %in% c("Drama", "Comedy", "Thriller", "Action", "Adventure", "Crime", "Romance", "Sci-Fi", "Fantasy", "Horror")) %>%
  group_by(genre, id) %>%
  summarize(title = first(title),
            production_year = first(production_year),
            budget = first(budget),
            gross = first(gross))
```

```{r}
q2 <- "
SELECT ci.movie_id, ci.person_role_id AS char_id, 
n.gender, rt.role 
FROM cast_info ci
JOIN movie_info mii ON mii.movie_id = ci.movie_id
JOIN title t ON mii.movie_id = t.id
JOIN movie_info mii2 ON mii2.movie_id = t.id
JOIN name n ON n.id = ci.person_id
JOIN role_type rt ON rt.id = ci.role_id
JOIN movie_companies mc ON mc.movie_id = t.id
JOIN company_name cn ON cn.id = mc.company_id
WHERE mii.info_type_id = 105
 AND mii.info LIKE '$%'
 AND mii2.info_type_id = 107
 AND cn.country_code = '[us]'
 AND t.production_year > 1980
 AND mii2.info LIKE '%(USA)'
 AND t.kind_id = 1
ORDER BY mii.info DESC;
"
crew_info <- db %>%
  dbGetQuery(q2)
```

```{r}
# a table that has a total number of people as a column
# in order to join with crew_short later
crew_total <- crew_info %>%
  mutate(role_in_movie = ifelse(role %in% c("actor", "actress"), "actor/actress", role)) %>%
  group_by(movie_id, role_in_movie) %>%
  drop_na(gender) %>%
  summarize(total = n()) %>%
  group_by(role_in_movie) %>%
  summarize(total = sum(total))

# specific info about gender distribution within each part of the crew for each moviec
crew_short <- crew_info %>%
  mutate(role_in_movie = ifelse(role %in% c("actor", "actress"), "actor/actress", role)) %>%
  group_by(movie_id, role_in_movie, gender) %>%
  summarize(num = n()) %>%
  drop_na(gender) %>%
  group_by(role_in_movie, gender) %>%
  summarize(total_by_gender = sum(num)) %>%
  inner_join(crew_total, by = "role_in_movie") %>%
  mutate(prop = total_by_gender/total) %>%
  group_by(role_in_movie) %>%
  mutate(prop_female = first(prop))
```

```{r}
# code for the whole crew in general 
# a table that has a total number of people as a column
# in order to join with crew_short later
crew_total_2 <- crew_info %>%
  group_by(movie_id, gender) %>%
  summarize(total = n()) %>%
  drop_na(gender) %>%
  group_by(movie_id) %>%
  summarize(total = sum(total))

# general info about gender distribution for each movie
crew_general <- crew_info %>%
  group_by(movie_id, gender) %>%
  summarize(num = n()) %>%
  drop_na(gender) %>%
  inner_join(crew_total_2, by = "movie_id") %>%
  mutate(prop = num/total)
```

```{r}
# codes for actors/actresses specifically
# a table that has a total number of people as a column
# in order to join with crew_general_acting later
crew_total_acting <- crew_info %>%
  filter(role %in% c("actor", "actress")) %>%
  group_by(movie_id, gender) %>%
  summarize(total = n()) %>%
  drop_na(gender) %>%
  group_by(movie_id) %>%
  summarize(total = sum(total))

# general info about gender distribution of actors/actresses for each movie
crew_general_acting <- crew_info %>%
  filter(role %in% c("actor", "actress")) %>%
  group_by(movie_id, gender) %>%
  summarize(num = n()) %>%
  drop_na(gender) %>%
  inner_join(crew_total_acting, by = "movie_id") %>%
  mutate(prop = num/total)
```

```{r Join genre and gender proportions}
genre_info <- crew_general %>%
  inner_join(movies_short, by = c("movie_id" = "id")) %>%
  group_by(genre, gender) %>%
  summarise(prop = mean(prop)) %>%
  group_by(genre) %>%
  mutate(prop_female = first(prop))
```

```{r Plot the prop of males and females according to genre}
genre_plot <- genre_info %>% 
  ggplot(aes(x=reorder(genre, prop_female), y=prop, fill=gender)) +
  geom_bar(position="fill", stat="identity") +
  scale_x_discrete(name="Genre") + 
  scale_y_continuous(name="Percentage", labels = scales::percent) +
  coord_flip()
genre_plot
```

```{r}
# create a stacked bar chart for different roles in movies
ggplot(data = crew_short, aes(x = reorder(role_in_movie, -prop_female), y = prop, fill = gender)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_x_discrete(name = "Role in the Crew") +
  scale_y_continuous(name = "Percentage", labels = scales::percent) +
  coord_flip()g
```

```{r}
# parse $ budget and gross into real numbers to calculate
top_genres_info <- top_genres_info %>%
  mutate(real_budget = parse_number(budget),
         real_gross = parse_number(gross))

# join crew_general with top_genres_info to get the gender distribution of the whole crew for each movie within each genre
gender_by_genre_crew <- top_genres_info %>%
  inner_join(crew_general, by = c("id" = "movie_id")) %>%
  group_by(genre, gender) %>%
  summarize(budget = mean(real_budget),
            gross_revenue = mean(real_gross),
            prop = first(prop)) %>%
  group_by(genre) %>%
  mutate(prop_female = first(prop))

gender_by_genre_acting <- top_genres_info %>%
  inner_join(crew_general_acting, by = c("id" = "movie_id")) %>%
  group_by(genre, gender) %>%
  summarize(budget = mean(real_budget),
            gross_revenue = mean(real_gross),
            prop = first(prop)) %>%
  group_by(genre) %>%
  mutate(prop_female = first(prop))
```

```{r}
# graphs about gender distribution by genre
# create a stacked bar chart for different roles in movies
gender_crew_plot <- ggplot(data = gender_by_genre_crew, aes(x = reorder(genre, -prop_female), y = prop, fill = gender)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_x_discrete(name = "Genre") +
  scale_y_continuous(name = "Percentage", labels = scales::percent) + 
  coord_flip()

gender_acting_plot <- ggplot(data = gender_by_genre_acting, aes(x = reorder(genre, -prop_female), y = prop, fill = gender)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_x_discrete(name = "Genre") +
  scale_y_continuous(name = "Percentage", labels = scales::percent) + 
  coord_flip()
  
gross_plot <- ggplot(data = gender_by_genre_crew, aes(x = reorder(genre, gross_revenue), y = gross_revenue)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 45)) +
  scale_x_discrete(name = "Genre") +
  scale_y_continuous(name = "Gross Revenue (dollars)", labels = scales::comma) 

figure <- ggarrange(gender_crew_plot, gender_acting_plot, gross_plot,
                    labels = c("Gender Distribution of \nWhole Crew by Genre", "Gender Distribution of \nCast Only by Genre", "Gross Revenue in the US \nby Genre"),
                    ncol = 2, nrow = 2)
figure
```

```{r gender-budget sql}
# filter for movies made by US companies only 
# get gender and budget information for each movie
sql <- "
SELECT t.title, mi.info AS budget, n.gender
FROM cast_info ci
JOIN name n ON n.id = ci.person_id
JOIN movie_info mi ON mi.movie_id = ci.movie_id
JOIN movie_info mi2 ON mi2.movie_id = mi.movie_id
JOIN title t ON t.id = mi.movie_id
JOIN movie_companies mc ON mc.movie_id = t.id
JOIN company_name cn ON cn.id = mc.company_id
WHERE mi.info_type_id = 105
  AND mi.info LIKE '$%'
  AND ci.role_id IN (3,4,5)
  AND mi2.info_type_id = 107
  AND mi2.info LIKE '%(USA)'
  AND cn.country_code = '[us]'
  AND t.production_year > 1980
  AND t.kind_id = 1
ORDER BY t.title; 
"
budget_by_gender <- db %>%
  dbGetQuery(sql)
```

```{r gender-budget data wrangling}
# calculate the gender demographics on the production team of each movie
# calculate whether a movie's production team is female or male dominated 
budget_gender_info <- budget_by_gender %>%
  mutate(parsed_budget = parse_number(budget))

budget_gender_prop <- budget_gender_info %>%
  group_by(title, parsed_budget) %>%
  drop_na(gender) %>%
  summarize(num_male = sum(gender == 'm'), 
            num_female = sum(gender == 'f')) %>%
  mutate(dominant_gender = ifelse(num_male >= num_female, ifelse(num_male > num_female, "male-dominated", "equal"), "female-dominated"))
```

```{r gender-budget plot}
# plot the boxplot
budget_gender_plot <- budget_gender_prop %>%
  ggplot(aes(x=as.factor(dominant_gender), y=parsed_budget, fill=dominant_gender)) +
  geom_boxplot(alpha=0.2) +
  theme_gdocs() +
  scale_fill_manual(values=c("#a081f4", "#f8766d","#00bfc4"),
                    breaks=c("male-dominated", "equal", "female-dominated")) +
  ggtitle("Majority gender in a film's production team vs. budget received") +
  scale_x_discrete(name="Majority gender in production team", limits=c("male-dominated", "equal", "female-dominated")) +
  scale_y_continuous(name="Budget received (USD)") +
  guides(fill=guide_legend(title="Majority gender"))
budget_gender_plot
```
