---
title: "Test Out"
author: "Ha Cao"
date: "April 29, 2018"
output: html_document
---
```{r message = FALSE, warning = FALSE}
# set up the environment
library(mdsr)
library(RMySQL)
library(tidyverse)
library(ggpubr)
library(ggthemes)
library(formattable)
theme_set(theme_pubr())
db <- dbConnect_scidb(dbname = "imdb")

# query to get basic information about the movies
# including movie ID, title, production year, genre, budget, and gross revenue in the US
q1 <- "
SELECT t.id, t.title, t.production_year, mii.info AS genre,
mii2.info AS budget, mii3.info AS gross
FROM title t 
JOIN movie_info mii ON mii.movie_id = t.id
JOIN movie_info mii2 ON mii2.movie_id = t.id
JOIN movie_info mii3 ON mii3.movie_id = t.id
JOIN movie_companies mc ON mc.movie_id = t.id
JOIN company_name cn ON cn.id = mc.company_id
WHERE t.kind_id = 1
 AND mii.info_type_id = 3
 AND mii2.info_type_id = 105
 AND mii2.info LIKE '$%'
 AND mii3.info_type_id = 107
 AND cn.country_code = '[us]'
 AND production_year > 1980
 AND mii3.info LIKE '%(USA)'
ORDER BY mii2.info desc;
"
movies_all_info <- db %>%
  dbGetQuery(q1)
```

```{r}
# top 10 most popular genres (most movies listed in that genre)
top_genres <- movies_all_info %>%
  group_by(genre) %>%
  summarize(num_movies = n()) %>%
  arrange(desc(num_movies)) %>%
  head(10)

# filter out top 10 genres
top_genres_info <- movies_all_info %>% 
  filter(genre %in% c("Drama", "Comedy", "Thriller", "Action", "Adventure", "Crime", "Romance", "Sci-Fi", "Fantasy", "Horror")) %>%
  group_by(genre, id) %>%
  summarize(title = first(title),
            production_year = first(production_year),
            budget = first(budget),
            gross = first(gross))
```

```{r}
# query to get information about personnel of the movies
q2 <- "
SELECT ci.movie_id, ci.person_role_id AS char_id, 
n.gender, rt.role 
FROM cast_info ci
JOIN movie_info mii ON mii.movie_id = ci.movie_id
JOIN title t ON mii.movie_id = t.id
JOIN movie_info mii2 ON mii2.movie_id = t.id
JOIN name n ON n.id = ci.person_id
JOIN role_type rt ON rt.id = ci.role_id
JOIN movie_companies mc ON mc.movie_id = t.id
JOIN company_name cn ON cn.id = mc.company_id
WHERE mii.info_type_id = 105
 AND mii.info LIKE '$%'
 AND mii2.info_type_id = 107
 AND cn.country_code = '[us]'
 AND t.production_year > 1980
 AND mii2.info LIKE '%(USA)'
 AND t.kind_id = 1
ORDER BY mii.info DESC;
"
crew_info <- db %>%
  dbGetQuery(q2)
```

```{r}
# a table that has a total number of people as a column
# in order to join with crew_short later
crew_total <- crew_info %>%
  mutate(role_in_movie = ifelse(role %in% c("actor", "actress"), "actor/actress", role)) %>%
  group_by(movie_id, role_in_movie) %>%
  drop_na(gender) %>%
  summarize(total = n()) %>%
  group_by(role_in_movie) %>%
  summarize(total = sum(total))

# specific info about gender distribution within each role of the crew for each movie
crew_short <- crew_info %>%
  mutate(role_in_movie = ifelse(role %in% c("actor", "actress"), "actor/actress", role)) %>%
  group_by(movie_id, role_in_movie, gender) %>%
  summarize(num = n()) %>%
  drop_na(gender) %>%
  group_by(role_in_movie, gender) %>%
  summarize(total_by_gender = sum(num)) %>%
  inner_join(crew_total, by = "role_in_movie") %>%
  mutate(prop = total_by_gender/total) %>%
  group_by(role_in_movie) %>%
  mutate(prop_female = first(prop))
```

```{r}
# codes for the whole crew in general
# a table that has a total number of people as a column
# in order to join with crew_general later
crew_total_2 <- crew_info %>%
  group_by(movie_id, gender) %>%
  summarize(total = n()) %>%
  drop_na(gender) %>%
  group_by(movie_id) %>%
  summarize(total = sum(total))

# general info about gender distribution (all roles together) for each movie
crew_general <- crew_info %>%
  group_by(movie_id, gender) %>%
  summarize(num = n()) %>%
  drop_na(gender) %>%
  inner_join(crew_total_2, by = "movie_id") %>%
  mutate(prop = num/total)
```

```{r}
# codes for actors/actresses specifically
# a table that has a total number of people as a column
# in order to join with crew_general_acting later
crew_total_acting <- crew_info %>%
  filter(role %in% c("actor", "actress")) %>%
  group_by(movie_id, gender) %>%
  summarize(total = n()) %>%
  drop_na(gender) %>%
  group_by(movie_id) %>%
  summarize(total = sum(total))

# general info about gender distribution of actors/actresses for each movie
crew_general_acting <- crew_info %>%
  filter(role %in% c("actor", "actress")) %>%
  group_by(movie_id, gender) %>%
  summarize(num = n()) %>%
  drop_na(gender) %>%
  inner_join(crew_total_acting, by = "movie_id") %>%
  mutate(prop = num/total)
```

```{r}
# create a stacked bar chart for different roles in movies
ggplot(data = crew_short, aes(x = reorder(role_in_movie, -prop_female), y = prop, fill = gender)) +
  geom_bar(stat = "identity", position = "fill", alpha = 0.5) +
  scale_y_continuous(name = "Percentage", labels = scales::percent) +
  theme_gdocs() +
  labs(title = "Gender Representation by Role") +
  theme(plot.title = element_text(size = 12),
        legend.title = element_text(size = 10)) +
  scale_fill_manual(values = c("#f8766d", "#00bfc4"), name = "Gender", breaks = c("f", "m"), labels = c("F", "M")) +
  scale_x_discrete(name = "Role in Crew", labels = c("cinematographer" = "Cinematographer", "composer" = "Composer",
                              "director" = "Director", "writer" = "Writer",
                              "editor" = "Editor", "production designer" = "Production Designer",
                              "producer" = "Producer", "miscellaneous crew" = "Miscellaneous Crew", 
                              "actor/actress" = "Actor/Actress", "costume designer" = "Costume Designer")) +
  geom_text(aes(label = percent(prop), y = prop), size = 3, position = position_stack(vjust = 0.5)) +
  coord_flip() 
```

```{r}
# parse $ budget and gross into real numbers to calculate
top_genres_info <- top_genres_info %>%
  mutate(real_budget = parse_number(budget),
         real_gross = parse_number(gross))

# join crew_general with top_genres_info to get the gender distribution of the whole crew for each movie within each genre
gender_by_genre_crew <- top_genres_info %>%
  inner_join(crew_general, by = c("id" = "movie_id"))%>%
  group_by(genre, gender) %>%
  summarize(budget = mean(real_budget),
            gross_revenue = mean(real_gross),
            prop = mean(prop)) %>%
  group_by(genre) %>%
  mutate(prop_female = first(prop))  

gross_by_genre <- gender_by_genre_crew %>%
  group_by(genre) %>%
  summarize(gross_revenue = mean(gross_revenue))

gender_by_genre_acting <- top_genres_info %>%
  inner_join(crew_general_acting, by = c("id" = "movie_id")) %>%
  group_by(genre, gender) %>%
  summarize(budget = mean(real_budget),
            gross_revenue = mean(real_gross),
            prop = mean(prop)) %>%
  group_by(genre) %>%
  mutate(prop_female = first(prop))
```

```{r}
# graphs about gender distribution by genre
# create a stacked bar chart for different roles in movies
gender_crew_plot <- ggplot(data = gender_by_genre_crew, aes(x = reorder(genre, -prop_female), y = prop, fill = gender)) +
  geom_bar(stat = "identity", position = "fill", alpha = 0.5) +
  scale_x_discrete(name = "Genre") +
  scale_y_continuous(name = "Percentage", labels = scales::percent) +
  theme_gdocs() +
  labs(title = "Gender Representation in Whole Crew \nby Genre") +
  theme(plot.title = element_text(size = 12),
        legend.title = element_text(size = 10)) +
  scale_fill_manual(values = c("#f8766d", "#00bfc4"), name = "Gender", breaks = c("f", "m"), labels = c("F", "M")) +
  geom_text(aes(label = percent(prop), y = prop), size = 3, position = position_stack(vjust = 0.5)) +
  coord_flip()

gender_acting_plot <- ggplot(data = gender_by_genre_acting, aes(x = reorder(genre, -prop_female), y = prop, fill = gender)) +
  geom_bar(stat = "identity", position = "fill", alpha = 0.5) +
  scale_x_discrete(name = "Genre") +
  scale_y_continuous(name = "Percentage", labels = scales::percent) + 
  theme_gdocs() +
  labs(title = "Gender Representation in Cast Only \nby Genre") +
  theme(plot.title = element_text(size = 12),
        legend.title = element_text(size = 10)) +
  scale_fill_manual(values = c("#f8766d", "#00bfc4"), name = "Gender", breaks = c("f", "m"), labels = c("F", "M")) +
  geom_text(aes(label = percent(prop), y = prop), size = 3, position = position_stack(vjust = 0.5)) +
  coord_flip()
  
gross_plot <- ggplot(data = gross_by_genre, aes(x = reorder(genre, -gross_revenue), y = gross_revenue)) +
  geom_bar(stat = "identity", alpha = 0.5, fill = "#a081f4") + 
  theme_gdocs() +
  theme(axis.text.x = element_text(angle = 45)) +
  scale_x_discrete(name = "Genre") +
  scale_y_continuous(name = "Gross Revenue (USD)", labels = scales::comma) +
  labs(title = "Average Gross Revenue per Movie for Top 10 Genres") +
  theme(plot.title = element_text(size = 12))

figure <- ggarrange(gender_crew_plot, gender_acting_plot,
                    ncol = 2, nrow = 1)
figure
gross_plot
```

```{r}
# all top 10 genres_crew ratios_over time 
gender_crew_time_top10 <- top_genres_info %>% 
  inner_join(crew_general, by = c("id" = "movie_id")) %>%
  group_by(genre, gender, production_year) %>%
  summarize(prop_female = mean(prop)) 
time_f_top10 <- subset(gender_crew_time_top10, gender_crew_time_top10$gender == "f")

# plot All genres
timeplot <- ggplot(data = time_f_top10,
                      aes(x = production_year, y = prop_female)) +
  geom_line(col = "#8f42f4", size = 1) +
  scale_x_continuous(name = "Year")+
  scale_y_continuous(name= "Percentage of Female in Whole Crew", labels = scales::percent)+
  theme_gdocs() +
  facet_wrap(~genre) +
  labs(title = "Change in Gender Ratio by Genre from 1981-2017") +
  theme(plot.title = element_text(size = 12))

timeplot

# gender ratio's overall change over the last 36 years for each genre
top_genre_percent_change <- time_f_top10 %>%
  filter(production_year %in% c("1981", "2017")) %>% 
  group_by(genre) %>% 
  summarize(prop_change = last(prop_female) - first(prop_female)) %>%
  arrange(desc(prop_change))

top_genre_percent_change
# the mean change of gender ratio across all genres
mean_change <- mean(top_genre_percent_change$prop_change)
mean_change
```

```{r gender-budget sql}
# filter for movies made by US companies only 
# get gender and budget information for each movie
sql <- "
SELECT t.title, mi.info AS budget, n.gender, t.production_year
FROM cast_info ci
JOIN name n ON n.id = ci.person_id
JOIN movie_info mi ON mi.movie_id = ci.movie_id
JOIN movie_info mi2 ON mi2.movie_id = mi.movie_id
JOIN title t ON t.id = mi.movie_id
JOIN movie_companies mc ON mc.movie_id = t.id
JOIN company_name cn ON cn.id = mc.company_id
WHERE mi.info_type_id = 105
  AND mi.info LIKE '$%'
  AND ci.role_id IN (3,4,5)
  AND mi2.info_type_id = 107
  AND mi2.info LIKE '%(USA)'
  AND cn.country_code = '[us]'
  AND t.production_year > 1980
  AND t.kind_id = 1
ORDER BY t.title; 
"
budget_by_gender <- db %>%
  dbGetQuery(sql)
```

```{r gender-budget data wrangling}
# calculate the gender demographics on the production team of each movie
# calculate whether a movie's production team is female or male dominated 
budget_majority_gender <- budget_by_gender %>%
  mutate(parsed_budget = parse_number(budget)) %>%
  group_by(title) %>%
  drop_na(gender) %>%
  summarize(production_year = first(production_year),
            num_male = sum(gender == 'm'), 
            num_female = sum(gender == 'f'),
            parsed_budget = mean(parsed_budget)) %>%
  mutate(dominant_gender = ifelse(num_male >= num_female, ifelse(num_male > num_female, "majority_male", "equal"), "majority_female")) %>%
  arrange(desc(parsed_budget)) 
```

```{r gender-budget plot}
# plot the boxplot
budget_gender_plot <- budget_majority_gender %>%
  ggplot(aes(x = as.factor(dominant_gender), y = parsed_budget, fill = dominant_gender)) +
  geom_boxplot(alpha = 0.5) +
  theme_gdocs() +
  ggtitle("Majority Gender in a Film's Production Team vs. Budget Received") +
  scale_x_discrete(name = "Majority Gender in Production Team",
                   limits = c("majority_male", "equal", "majority_female"),
                   labels = c("Majority male", "Equally represented", "Majority female")) +
  scale_fill_manual(values = c( "#a081f4","#f8766d","#00bfc4")) +
  scale_y_continuous(name = "Budget received (USD)", 
                     labels = scales::comma,
                     breaks = seq(0, 300000000, 50000000)) +
  guides(fill = FALSE)
budget_gender_plot
```

```{r}
# run a regression model to test whether the difference in budget between male and female-dominated production team is significant
budget_majority_gender$dominant_gender <- as.factor(budget_majority_gender$dominant_gender)
budget_majority_gender$dominant_gender <- relevel(budget_majority_gender$dominant_gender, ref = "majority_male")
budget_model <- lm(data = budget_majority_gender, parsed_budget ~ dominant_gender + production_year)
summary(budget_model)
confint(budget_model, level = .95) # obtain 95% CIs for all coefficients
```
